version: '3'

services:
  api:
    build: api/
    volumes:
      - ./api/:/var/www/
    environment:
      APP_ENV: dev
  nginx:
    image: nginx:1-alpine
    ports:
      - "4000:80"
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf