version: '3'

services:
  api:
    build: api/
    volumes:
      - ./api/:/var/www/
    environment:
      APP_ENV: dev

  nginx:
    build: nginx/
    ports:
      - "4000:80"
    depends_on:
      - api
    links:
      - api